apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-secret
  namespace: observability
data:
  ALERTMANAGER_PUSHOVER_TOKEN: ENC[AES256_GCM,data:f4yw09LJgryhJccdqbILvjL3NOLJBQN1fgh3o43hDzXlB66VoQDSzPZuehk=,iv:uiszBucQ+NiDnD6PPzKfB92Dy0wp7CQQ5zSf8n2RMCs=,tag:aJmvaa2XXjpHwrJ4Vcrprg==,type:str]
  PUSHOVER_USER_KEY: ENC[AES256_GCM,data:aWxrPiYOS+50WS2B0O2c2zvkrdzdFR+TCPnWwf+1lFSHhZQL6yM4/PieRQU=,iv:MqXADu//u39Fnj0kNsRq3yVbZEdMHDF8agRA/1+nn8k=,tag:SKGKZgHkbfk52uSnRepFSA==,type:str]
sops:
  age:
    - recipient: age1avwy9taq3crjetrljcd974j7q0wn6mxvcjl7ca7zlm79kv5h0ccqjj457v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKYytQRGMrSDVSMmp6c1pk
        a0NLTmlrUVd1OEt2aWFiaUtxVkVtV2ZjTDNJCkNqU3FrWHUxRFpwNFVkV2xDRXdx
        ZnNTZDhKdE9LSHhKZWpEOTNwVUcrZ2sKLS0tIFN2SEpqU2dTZDBIYWRhdjRNYmF3
        K1hpdkcvbjFnZ21rOWFtWUtsMkhIdzgKTFxnznDVsw9q4JHnWCyz8EJ+d3NB6vZt
        mxkD/6nZGHt/kVuahNbUWHfHkPdb7YH7IlH8OczrugsRZQmSPqpu4Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-07T03:41:58Z"
  mac: ENC[AES256_GCM,data:E368Gkfp35SrOJ96qCdAwNa2uPZGqIvVnypbSKPgaC87+un9Z7gJzx4/nPa/QoDTpG5t9P7M9j0vJ+TPVU+o89fKt6vZeGZrscaNUW8yrsSldZWUk3gnCR/p2rCRtx/UIJw29gPmOy7MUrkh5SGno47//q15GFtZHRF3NzI+xjY=,iv:pCV28KQbL1xbYNMGWC6EEi2dEMWLQXJ4YWJrIWaifkc=,tag:rCa3f3XUh9RmmUsODecJAA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
