apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-secret
  namespace: observability
data:
  BUDDY_HEARTBEAT_TOKEN: ENC[AES256_GCM,data:MPbzxBkDBJkPK4EtDhIvgKETlSfb+E5od6K14Q==,iv:VXL3B4+cRglByLMS95Dz2x0LmXHLv4tW/kVFuEZfHRk=,tag:Sp8ENCQj7EZ29UbeQZg1uQ==,type:str]
  BUDDY_HEARTBEAT_URL: ENC[AES256_GCM,data:azLHrKGJ5S6eSmEx+kWK36jjHcJsQfs2B9AgeOlG9NUArnUn40xKycRqkJh2uau3TL0p5D/CzDvMSzErY2ebn3XClMWs7CMXZ8gi2ahMR1aUp8CoNfKcIpzDGg==,iv:L7RgiRiCdGLclHM7/pII/3vsztjd2/wXQeEDRwr/2kw=,tag:oFMTcaT84lDvMOlMTkKyHg==,type:str]
  ALERTMANAGER_PUSHOVER_TOKEN: ENC[AES256_GCM,data:jEJ5K2hb19Wz/e3wHFGqcZSORJkovv5wcSJgNY/kxZkrYw==,iv:EUkxBep3aTwl8QvrtHCdk5bSWZLkvhwSjacOhjfeUKY=,tag:QXS8WpU0+IwdqEbCz+9amQ==,type:str]
  PUSHOVER_USER_KEY: ENC[AES256_GCM,data:+14K5hGi+ZJgK83eEOEEpTCKbaInrsWd,iv:eQnxH+uGQ67gyy91pSIScZa/x15VORwflMyLuAw/PVs=,tag:D5Au8ZjXdwj4lDiqKayDRA==,type:str]
sops:
  age:
    - recipient: age1avwy9taq3crjetrljcd974j7q0wn6mxvcjl7ca7zlm79kv5h0ccqjj457v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVS3MvNzUvcnpVK3R1R2JO
        MmJwQ0I4ZHFyYkovWm44OXZha3NCK3VZb21BCkNQSWlCRTIyQzk2bTdDV0d5Z0Zi
        aVhVQWpJeGE0NlhnRUoyeExUZzNkT2sKLS0tIGxvR0VlMzA4amk5K3ZiT09OYjQr
        MVhRbEdsbG1OUExGOEY3MXZNMlBhYk0K8Qz6VC+8pY5Ohs+uDmsSFJV5ft1xmMTs
        PKqoaFHokWw836VvSqL0gjyiG+DCrNWjnl8jOettQvGGi5i7PJ2/Vw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-07T01:55:15Z"
  mac: ENC[AES256_GCM,data:EWh8+4SpS8J7x/SZkBIWaet86KFTnj+9joOpUhVwcph0/XkrOwIIceh6IVVN4ZcppL9XXiU9CyIIDZzNKGChq8rnuJjteauLVO+lE/nc1Pz++AUIFpMIOViI9/OYI+3o6+frcggQ04Q+1szUWxogma4xYjHeKtSzUfgWcPe7Cg8=,iv:NM7t9aPfZMdYztZlCW1N1cBmOCv53FM2Odrpiikr0/M=,tag:C8crQlSejifieL4hSvbk/g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
