apiVersion: v1
kind: Secret
metadata:
  name: op-credentials
  namespace: kube-system
data:
  1password-credentials.json: ENC[AES256_GCM,data:y+EbPn6GZwtE9ed1HM68aHkdved1A4+zPguEH4vPk1OcCLi7YgzJ0W/qDrcY23NQlO8oYEsQzc/fNaDc4isvTxr/R+6m0rK06ECYqeZ/EtBs6c1l4sLYgsXM6ReVrk2JOsnsM7ilFJfycx/PGlKzw0dySQQFYkdewRdm24Ztqo2snXTxSoGA92kWgbgZTxq1sd3b8bZZvJWxipPQkIp+X0eKHSIGlCUXiCDoXo4suU5rE+C50NWXfPoRNVWDZTsrjL27s/UN5baFPga1oB7bv9FoqgLs1R/+/UrBtw1BJxmOcnbAZgEx1aQ95Xy/O7JsTROHOc+1jEsTscgPkVh/ZuUBJgbAZ0AlWVJPmaiA6p0ShmxRbtHtRLbHZ0hbU3SlRRO6eaoztNFOzsZ9ahgmcEwB8Ot61G6MBbJKXmVETmNgDQr0TDnHcoY+U+d8q5WdzjmzXLZ/oAxC95AdrGRTlN6aGOsgQgkjJHSYn7UZFw26JBcH/SzdnAjGtxXQ1BCcOsC6f9MitaBLP3YNAjzdDqopWsGJxJTk6UmqQzD8JP/xE2cm/PXE0xrY8kqimdZ59DTsvrbKBurF6eEuQdBiHI2f+Dtg5QVEyIRzneUjSRXmQ9wRFGpwf+Y80/GrQAb067+bt8KdKanMSevT13MoMngxmC5uy0l6OKnOl/QdbsUg2vKJNuhu8ySbnFBPnZzB8O+NkFQTUEt3VpyuLEexkOhlCzz1wee9l42OFByf+cIUEorHZT11hK3BYYvU7/dk5HsygZYAQJc74GEplWFHa4XSGpZEaJk4ItS9TLnG+PWAI+mJQSu3+PhXkEArOumCiA58Xopcq5HxzYhUNEnet4X0bKFmSm+zGefQUve+HdpSHeolJmoLEAIRtZNNdTgidCXgUNRzd/VeGK6fy9wFDl4WpjD/8yry1anYgbFbOck0T1v46Mdu95HUzHR8qSSAds51ezBrMmD8ikaxsWCfpZW57RWb7y5n6ZUGaMBH/LYS2m42HGPbAhpPu7ORK7wwmvUbShBB3bxWZRBS3C0Y/mWNvBudVzvEj0vYGWebJVl8PtcjbIHwKXFjqUzdli5silufa2D7/4vomwpo/qKK+THM9p5e+T5jIoUFsWgxqjomFJ7Bk+gb9z+PH+TFrm6274uxJlaPB/fmxc0nxXoj2UaueF535mzAgwad4Q/Sr8Vnl+GZWBHddWlW05ycVleEkFfILWbhkNZ2d2bj3naOxQoPlCA7KuYRhIrMWYiGMlVGz3MxxOLiCdmExFaqfzuzstXT5BVpJZMEFcM9BC8zXYhQIzJYPRijfSV7urjdKs0plo485YCynW7eXeffGeOrRig9S4EJ50Y8ux7chA+JK5Yvw9QSUXNsjVK0x5CAwatx5iUunOQwHRubTFs5ufHBQT+FbPbAUrDTCaozVdEhOziEKfPoYhZVekz9IVaDyxSQ1CrYJzd9ufNuO4ffyATTJZQPAYih3cnPzNp6TGhf/FG7edc0G+VKyRFeFSlFVIQChJOVjMbewe6iRPajfMNrTF/nSHSrVlnirhVMq4ip3tLh/m3UJw19IzUHJaXi4CXjjgk2Rfc1Px6G6LQEdvsucnzZhyzur+wSrEkCenDNo/YgO1AaXv3HBR5WkcyLe7NnhlA61ueJ9c8rvqcbwY8CMKptFSUx0YSG4YP+0vyWcJDH+KKBiuMpwtynlP6wzAvYkIM1nFQwoRXgW9Gig1S/qMa7wD8BOMDOMAwpqlp4QFBErlh3jSvr/xGPe8oQwNZmto/2uTDaHRUeXp8AoRHRHpY88CSrmaEnoztdU3z2VZJUaWOlRqHFJnc7uL58ihGFGLgaxslg3u0bE/I2ifSAmZNWZH8tBnsSKeZf8KiWLUoF22HL0j+RnSiSQ+fUgZA4mDe9vVUMMTKcFvgUyMx4mPs2UHb8PfbPJ6wtEw/AWuhKI4BymxmqA/pRr/D6g0GiWYNFFwKcUfA9KUusiXX4qqKDLlbCtcUrdR5D1skSFH1pwWBFKTrQ,iv:SjMOMqhhiINVLAZjKZV6pAHBXh7t8Jr54lnUc51aW4s=,tag:P1WN+2kjCqG/ZuNkSStanQ==,type:str]
sops:
  age:
    - recipient: age1avwy9taq3crjetrljcd974j7q0wn6mxvcjl7ca7zlm79kv5h0ccqjj457v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArMlhiSk9HSnIyQTdXQ3pB
        eTVhRk1wRERXdGhBYk52d0UzcWRwWWpqR21vCkdtdllTL0wwQ1VBcGcyTFBDSTA5
        L25WV1BqNnVvR2ViMHBIUTlIcFFYNTAKLS0tIEd4QjdIK2ZhYVVQMEdHaWdwQjdN
        SiswR3FrcHRaY1pXY1FiMU9nVzlyMG8KBLvMKcJbsoN+LL8MQZZZxk4t0tD+LkYp
        qjBo9b02GW8jTsrtLMVTLmHVd/8fJaD15Lfllx+sof7Rxp/L+gcePg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-05T05:18:02Z"
  mac: ENC[AES256_GCM,data:kCNjYb7qQkvow+2WNIR0OaJ+qDTKgFMI0Py3HutRKJJqsNi1+AeTpWnvQBCt0dFiCfGOlVaPko/Yp4d/UIvzcH/0pdm51EoNLgHdPgJdaZ+j2H8854PHgoHXmzvS4yTSwLPmAo+0i+vnCvpb7ooDGWC+az2sXOCKuxcr5sXdk1c=,iv:8qmRF2FoYmBz4mR+ixLK+Qq2hStiQp0CuysldV9DVP4=,tag:wo6Uk+hpzUMqHT0mKEyXvw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  name: onepassword-token
  namespace: kube-system
data:
  token: ENC[AES256_GCM,data:L9tr+NW86D858ZYNRixvvp6tMY30Rvhlod86ngbYXV3tvTwn0TiT0bQkUtdyBVNqwZK3uIAkiSr1bABl3u+vuWfPNLtc8FoCiMzOQxNqJ+aC6ay+uQZbvL90k9odsX9i91YM2mnumI845ATCx1Lmmb4BxRXU/0eywtBuf8KfnhQWoMAqd5JsW19dGHmKJY0LUh64GndSq5RK4WorIEqBsbkyQ5MFzAWgBk9xop4tvFEgJ0WzgBa8OvML/aaOSCqT8S3GruFY/CDU2ZgYJ1mN9o+UjpDPhv4Zi54Y0BIzq6acndGKhkxc1vRJ/ZDYnKSPLUZaODHATfJHnDmWcS6ndS9J/xi+SZVvpbPxPXhyVcxAM5K+Q9bVL5yX475y/MVNqMVHLzLoNgLnC5CO+IO5sYD/kxyat20JzDmboYEekAHrAGlP2+Kk/FuSGPr6/IQ+zqEz+x5DeF/+yBE7XVZ6j2XFFyQo4RYwIX+lbNcMAlZwVf298RRtO1IUruf6dW7kBfN4Ug6dfIImoW00l3qwqSmnG//SPQ4FYSIdwCEX0VPMx+KS+gjiT5fw1fbQ3z3D+3iFTbrLsvRDz1yasrsQs7QzASWPXAaafT+B0X47RY2gLR3OD5xyBkH2ffXyFQC50U5px+MjTG6hiZkBZnjP8lxrVec6Lnzpn+T+kq8tFLKR3z16RJQO+n6qdo7mKGTdQENybquuR7Z+N4hFzxRy5Lgc9rxJo6w2M372Tgsmykw/8kiKguA4zKajXCjEPfdulP5zpwXPJ0W9pbZY5ZGr5oTVeOBtI+G6bgj8pnx/dMXAwGUyAn1ewgYVqKNHDGt9jy8hM193Y1XVyH+R1zZWcf4fOZZwBKHVgFt2CQwWwzVa3HcEzvZANeYLWrZk1Pr98K8o/kNhIy527BDB/vHCd+tpAK1Fe3bHPSD0oi5WxYZkMFr8DdNGM2iaHTCfI+SxhH4rXIthDStVmtsGPUBkmrZ0oBPP37isfFnoBb5vnn+mHbGYkhYQSOv6G17RZB8GRN5Dd6pYWynC6JIXNm3eKHJEaTYy/v3eJbvR4MNHJQanEaAyZagkHG0YdzTN+JSaP3OtAe9TIJfdfkNqv3kzj0z0kGCU7YsuZipZLKDXVzDBG2RASIkc2A==,iv:CekjjhTl5DHYcBjF7KDunBvS+FK8YVc1mQiD/mlTxCI=,tag:rxcra94hbZlQYCWtcWYJYA==,type:str]
sops:
  age:
    - recipient: age1avwy9taq3crjetrljcd974j7q0wn6mxvcjl7ca7zlm79kv5h0ccqjj457v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArMlhiSk9HSnIyQTdXQ3pB
        eTVhRk1wRERXdGhBYk52d0UzcWRwWWpqR21vCkdtdllTL0wwQ1VBcGcyTFBDSTA5
        L25WV1BqNnVvR2ViMHBIUTlIcFFYNTAKLS0tIEd4QjdIK2ZhYVVQMEdHaWdwQjdN
        SiswR3FrcHRaY1pXY1FiMU9nVzlyMG8KBLvMKcJbsoN+LL8MQZZZxk4t0tD+LkYp
        qjBo9b02GW8jTsrtLMVTLmHVd/8fJaD15Lfllx+sof7Rxp/L+gcePg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-05T05:18:02Z"
  mac: ENC[AES256_GCM,data:kCNjYb7qQkvow+2WNIR0OaJ+qDTKgFMI0Py3HutRKJJqsNi1+AeTpWnvQBCt0dFiCfGOlVaPko/Yp4d/UIvzcH/0pdm51EoNLgHdPgJdaZ+j2H8854PHgoHXmzvS4yTSwLPmAo+0i+vnCvpb7ooDGWC+az2sXOCKuxcr5sXdk1c=,iv:8qmRF2FoYmBz4mR+ixLK+Qq2hStiQp0CuysldV9DVP4=,tag:wo6Uk+hpzUMqHT0mKEyXvw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
