apiVersion: v1
kind: Secret
metadata:
  name: op-credentials
  namespace: kube-system
data:
  1password-credentials.json: ENC[AES256_GCM,data:aHPpEpxoc5AdrxniOvdkjpof1ohBgzpjKofnL0rS94TlEToCA8b3LFo5Njy7rGF2j8Ic1DkyoeeKyBJhtnrYWBNAhrpgrCgwGT2bDsP3QsW0IkqdUDUcKXLij5MSrTpL5sbonBei07NzXUrLKasAMdIYmp3YHH8FOe/EKUvjWZkDLBLRy2UeHNS5/Zg88W0MeP2WLnMCNBU/2DwSf90RDv0eLS4AwmIx7gE08o8Wm63Vlm71DbDXX4cwTkx/O2o9cH1huGURkBqtm0r7YjI8PLplofXJWqjl1UwVlCFx1eYYtRJucirDIIdfIcd/d9tyK46ak4f4RmWpv/kloYuZMMs6Fhuvjx8t9bvJpdMeS3iDOQHP9FgjZaiphZb1XVEsZEIV72Go8G/cEGh6HgPQRry+3Y0At92SodsvaOGoNTj/TsB84d8yHSJNOCQCOZy9YBfD/u6ONV7bE/w/rtRXTiyfTmopvwHxol+tutuBgzwVS6MbDCUC3AWLAjhyF+9RnY+dAAvROncneyI7fY6pCN+E3zuRE2oJKeNP9bklQEQ6V3lStTk/42wYlxK25btgXiFd/XbURVjguF3oZlBsqwMzgar2oVPF9M8scwan60VjIBbaNzJjxbauhodjbwnNKzegirtHS8EU1br6hek0T2esVZMNRekt8lcoCuIIMbDTeTgFKdAYPaZeTN1le7IWYAlNtO17ggCtrV5jatwI0z56bnLkbQ+BB/ZRDqoeYft4ZA2Z6vy/Kw39E6Z87emvF7v2pU7Mr8/eRty10tCFozuYZ6TVWI1encDwd1xfRZcFiDRzd5QTQjne3gU2tvZkisVROfqYuDWFjyLBdtH7b2ZoBhjiNAGfOT8dEICv5oC+LXwUXrBQTX3YX0szgWNqC0mJaaugiPBWPQ8Hb5Ny0QyeH2a3BbheBXjedzOK0arIIeZK46f61XcA9mZMR35w9r4YcLfOsUP/3RvNdHbvux2VE6mX3AGWO/4G17K17h0oxx6Y4fYvuNCFY89PgYY+IwGA/EyuzrEh4D0oMqKhV+Fc6p0k4UXDRF2ErQrVsS4H7rGh8PdSEuBNlz64+cnE5sRT0wiVzhwRQHpQRx3QarfH96Y2dKMDwp0tPoOMe+7SAFoKEuhoRwev9y/+1ft9uAw2qJ0ROcHmHtHoXwuC2P4adirCKGDezVF5/bnPGUFT1h1l1El2RWOjIAKJl18PqNqIyglGOoDOPo6FncN1m9IpZv9H8Bbl8vNEYMBSqhNfDxUHO3z9JEOtJ8N5J3WjoHIcZHidaBi8ufUFKwB4KUFpn5N5EjSsxVXaRSc5Nt2J3GS4595pgBKd1LWne28IN0Py7BjkhgadkSP2xul3df4g6jYs8phKy7lRcWRVz8FpvuC7kH5VNmlPlUqCRd9+o4jpfzim4lashcwtG3hf32dCxCDO1tyc64eySiVtgj+r6gy6VkMnau/XJKFdMdLZMRRcX3ytns2q9RYizuf2qsCXjCa9eSeZC2taxwyrCnwteM5GHResIrLu32WQBocDla/R1zDNtrwdAJBGrJ7j0gB8lFKfYZqu+0dLJ+yVagMGldZrf3NlfoSDw/of9TX/a0jAmMJbxtXnkC/OTpeTmz3U67OiVoNZEuRSLiOk2hFrbrPhvQzPo+7Hcy7s4ElLSZznKXHronV5u9ftA964rNfMeqPG9Oq73fjjbhVEebxe7n5U61PXBhcY9SMb4ug8PLOhraW0KTGGcbWHNIasXbms7TIIiCBCE9+jK5D+epsy6jnrz75ScFTJRJIDmJacqml/tRV79jqLWoqTueR7zjYrheCkSDFW6TW+Mmwhryan4YbltZrGFbwK8qr9F6bOP8274i1VbYnvNs+zOhSTeF7+loGxhj2eZ9NYsY6l8kKXI+fuWOottc7pWvVdhuwVDmxUmRDG1nvptRzObHbGFE17O8SxBapFmWDt88NbxmTR2UCKhX7UgntbWQlpNb7AAuNHtZRz2ohQltcZvd+HBZYrQxoHbQ==,iv:Yq91J4lLqevSI2taClGfHvfOf5r0Xd6GYfy5FP1j6OY=,tag:1cRojRwoqza/IEtKbCtfRA==,type:str]
sops:
  age:
    - recipient: age1avwy9taq3crjetrljcd974j7q0wn6mxvcjl7ca7zlm79kv5h0ccqjj457v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDNHEweURySk1nUWtLNGhh
        ai9Dd1h4aVZTZXd1dHdkL2czcHZiVFd2TzNrCkNwZmd1MVE1bzRwRFMrajc0RjJN
        c1hEYVJZRmR3NWZjY1piWEtTREdJeGsKLS0tIGVzZ3MvM1RKblBGMWxYTllVeW1p
        TFlta1RJNmNudzlRSWNXYmk0R3BkM0kK4yJcc8kcXzk5M67mMk1fxvL4gOmv8aSc
        E1unrVJ1UY9eXGAREViFTqpiFOuyckhnPR3CGz5rBKcVBlMRkbj/Qg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-05T04:43:13Z"
  mac: ENC[AES256_GCM,data:WWAIM7pa9y2emd4erZhzacKs98p0mGlUuk2BoeP4EyLFG/sbdT46A7AB9amKWhy+6hWb34tCg1qngJvVSVFOHRDRkoF/bizS73Eqm/qB4WiUESKMcc4R+zmmg4g8EqWK3bpe9LyfyNY541VMnaaAZYQAJR8Odf5BxHsbFo8jL4k=,iv:a71T3reJtOUIFGXLoApETOR9skvwY0uC60GRR5J7NkI=,tag:gwmRnRjMpZRK6Qnu/yFlGw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  name: onepassword-token
  namespace: kube-system
data:
  token: ENC[AES256_GCM,data:O+o6kAV0/DFEa/Eg7sc0v9LFuICMcofJULE6S9B6+Ko1F82qVFH+yjPpL0PrHn91yUt6KvkoIEZtrDfpEwYrntuVNGzVDnapiFMChmHy6B3OgxqOoIvFy5ZS66m4/fKUvzbasFGrhxX0l1ZcQJSEgtXw+IzNXfKBgW2V2tPvQJ9GU3p6oFJLRGBrWwv0gIzaP6ccD9LABz6kbxoRgx4dSnKKasDSZwqeHS+j0LKfH/+LYdbxTiJOvEVImGrS+TGzrWhxy5VO3alCc0pBFffLpmLv2cK1yyE79PJpsCeCGxTXoGVuHmx6BbPgOonxBjWPDhGJLNcW1DpnyP/94ibYpzLLUlxxs1saW+gefrCs/DMkk5K+oAnM1ECCjloA0HcxUuG5v6WrlX4Od5rApbEb//ZPGLgEYqtY05npm2tKWbtLoSQtRizgLJkdHGcsgJwv7GUbgNr8eSTvwOTZNPQ1n3t1DENKCos7EAX3ZiwD+SOapNSQ/CZ9f7scb9m/WemQfkPGEtiAdcpa/5k8jLI2jShk/a5b1wq8e6UHv12cXOY2+rtSTI8wlIyhKNvbGahaPjpp0nYIX8Gfkp/fKGNOv+Lbz7BXvTffY1qPz22ThldFwIlVNINXtiRZT7Ja2DGFnMIP6vYJq1v2Kwp1Eyfi29PPU0E8C7MC62WXCCVrfYSO1xjUVL5r2dLIa5g9nCpQKFwaGu8o59eT1Z7IOUltJRi91Zo0GkRzxuYI1dBd1xjS/DXqdEOwAKTvuZuUvacnGQwPXBXZcDiyejSeuvQJZCacS/AaHXIixln9AyunGER4U0QwXuqOHSDcnDsQlepr6Tzdb2BoAl8LeDcYV7oH+LQ=,iv:NmW2Uh/FgEweZg2SZf3yZEvKLv7vfdzGDBaKQqnhF48=,tag:7gRLzhqxqFl5AJIKyXgL7A==,type:str]
sops:
  age:
    - recipient: age1avwy9taq3crjetrljcd974j7q0wn6mxvcjl7ca7zlm79kv5h0ccqjj457v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDNHEweURySk1nUWtLNGhh
        ai9Dd1h4aVZTZXd1dHdkL2czcHZiVFd2TzNrCkNwZmd1MVE1bzRwRFMrajc0RjJN
        c1hEYVJZRmR3NWZjY1piWEtTREdJeGsKLS0tIGVzZ3MvM1RKblBGMWxYTllVeW1p
        TFlta1RJNmNudzlRSWNXYmk0R3BkM0kK4yJcc8kcXzk5M67mMk1fxvL4gOmv8aSc
        E1unrVJ1UY9eXGAREViFTqpiFOuyckhnPR3CGz5rBKcVBlMRkbj/Qg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-05T04:43:13Z"
  mac: ENC[AES256_GCM,data:WWAIM7pa9y2emd4erZhzacKs98p0mGlUuk2BoeP4EyLFG/sbdT46A7AB9amKWhy+6hWb34tCg1qngJvVSVFOHRDRkoF/bizS73Eqm/qB4WiUESKMcc4R+zmmg4g8EqWK3bpe9LyfyNY541VMnaaAZYQAJR8Odf5BxHsbFo8jL4k=,iv:a71T3reJtOUIFGXLoApETOR9skvwY0uC60GRR5J7NkI=,tag:gwmRnRjMpZRK6Qnu/yFlGw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
