apiVersion: v1
kind: Secret
metadata:
  name: op-credentials
  namespace: kube-system
data:
  1password-credentials.json: ENC[AES256_GCM,data:R8fFntRlXgNb6Z8tVuM5XU1dvFOc8Qa34Oo3KyFR7A3a1PPAQH1WLm0wgr6G7g82pYv+xZEY8w0XvaLj5ekKvyJDOi4GFHrEMgz3tvYyXHG6I63B8n8p1OhlLhkaZ7JY6WT+NabL24tFueOLjQjaRtLHV76SMGn2Sk0kDcAa6J6zdi8PBmm0Z+KuXEDJ2Ywb1B5+Ux6E2VCKKLpFm6Xdn4w7Kra0wNrUpBuE3vIzZNLcfuUksRY4Be7s+RIoThrtUc7uO5ylTJVJ3gppXFewgylmsfnDwnem1vzUKGonfeFZ2ymnsDUHCR4TTSce+2CkkhGNKamwX2wvFAxnAM2+Ya3O8PvFVua9msIF4TjJAVjhuBllH8JfrulkxhKFAD1qbr/hp/BIajHDW/oo3eOCFa5j4mMPWGIuqmLk7CxqjJVGXm3BLc832TpvTjLsNlSgtUCHEEBTIHX+o4uLDtcLMrhVwBXFr56YQcgRgcfa4HHjMRH9hG8OjzMp9003U+EPIWtZLz4DgSZR72LqwXWjggz45TgSUgAy+m55UzO5CZxXzFa+/7G56ndTDMyjj2JNdJAo59nx94aTFypVH/4oFgV0YfvWEQSKlmw2Q5fIhbIH8j7fBpMuB7wGhfN7gUsTb3kSaH3v2L0HDU4d7LI0bPiWTpvN0ZJ2R0BNim0clYGtpUe4SFrU798XunnGlLN8DfJza+EYB3GwquSfNL9yn/GF3jBflV17I3uMAQqxWXC4uYwecKjyFbbgwBiJWkOgFjnmJYDLGJesPV82S4xFkivR99qq2E8ECt1VxEITrkwT3ddCz81KlKBYfp3qFbAmIYASeau21qXRfPIZeDNgDELhdROwgMEx/9ilW5tx9o6GKpCfIE5tkEGSVW5UU7pTMnr/C2PC2MKcRkHgrwlzwWAIqOE8ySOvhKLfkzs2s803Xgq+j9zEwGz7DXUcFqoCVcpjIBzwEbTVkWd2SFAKmYk6TanBJyde1O+w8Ry9xZYoC8f9M7ugbo/6zaxMoY97lAXsY5HGQRJnL8AzRTUYfIQVPqwHP3luAXiRnFX0yZFER8RCa9e0cxnlRUJgBxVu1deF4Gz2kn8wxSVzWxXasw7S5MGuIQMIkvEbRenPqX/XWsJd59Hus+p+D1iU0Xo4V4eNunDLfj5QreMrFzK/i3tZrd5pxn1a8b9DYfj3oEMfG5Ml9LRv7rwq3wEwQfLtQHmsR9e6qSdbqrMDn4MFRCLiGMX6I3/aSTqUQ0cWcjDMVxxqul+6CB8K3cvm6sAyiFaa1Ws9cH/AtfQ0ozskoTOeK5QRo05DE1o/LuQlKpTuT0SvLmS5LMyoau5vlA1UoJTXan554Mq7PuB/7wif4w3HFrKdDtZZ8MeVHhcrTi9kY3nSN5yxNObyl30f0NUZGVQZDIBNGdME2rcuuutAVpEc5959+i5Z69/1CW9V93uSXUqdl9qB5rQlwuxJfr59x7h7R0IYh0CTiTc9vHrgAcjXDyftQH0gcnAb1ltqyY1ZMHOVzocyPWS2iMyg/0WCpyxmFk3Ra9xJkMNYyli+wxAdkpXFCpMzElMOwmtdP6ZxzmSQtZBtJX66hNAwgaSjtjumD9Kxj3ovY7IUdexOm3T6sblsowYXve1wAjcgwOAz9u2FhgvIExJLjOxL3YVvnt4O1YIMcw72Nta2OKt8sNfg90iP9sKZUgUMdkl9jQPHpz/tSL0SAEJYLe+y+SdNVNZU/773795pkz1K8WGANmGgPaIwRqYamoIXHctpIxbe3zYsTDYPSVlQA8XDI4Svs9+jMZq6ofNPzs1DOTLESckQpewrrPfG7jtYnn1UD60CGQyLGKsw+wllI/TvCYikCICZEJOjZwFSaP/0rTYD/KU0AVuQglXWpDBNhy4xi559DduuI/8EjR/HnNQjnUnDCWu81LfBRTMOoOsN4az6hmdGAtoWd8xQDCJYM3hpJ3Vw/tkl50mgVH1lMWrA1FwjEcTrzAUcSxkRTZg2OboFucY+ovHmVtXR,iv:KAUxmRldb6GAfd2P9m3Cso2ORqZes4X/Ax7OUen2NfY=,tag:9u+d0N1keEKndXyWoCWC3Q==,type:str]
sops:
  age:
    - recipient: age1avwy9taq3crjetrljcd974j7q0wn6mxvcjl7ca7zlm79kv5h0ccqjj457v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsdWpVLzFHcWtRQytvNnNn
        bkVWOFhmWjBsWlFOeFJoaUtJbVRsV0lqTUhNCnhrTEIwcjRaRXBJOHVxaG11cGJB
        TitUMEtTNEluUlVYM01ONTNuRWxMZWcKLS0tIFJZU0gyanR0UTE5bHZPNnEzNVBR
        ejVvSHdqOFB5MDlXa0JDV2Zsclh2WmcK9rTotI+H5H1F47bC2T+5WZoXxvb2I/Gp
        OzXSJ0se+Yz8Zsitut8DsKEXhiNhFBeeMk80jVjWLmAeRDV3pY1Q/w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-05T05:12:44Z"
  mac: ENC[AES256_GCM,data:cYR/76WNaJifiD50Icbg3nyf4JblFhW/IXniR9a6Vr94dF7Z1WGDDpXnicCrvwnCrN6rV1dj2vbM3l5WVbzFEPNszVEb/DFteSzbN8xZ0B3fNts9FIFWnrhya5wc6/NiQXxc8G3PiIzt2QMBhN/Y4cNtYF2FXCqVjWm15cVHzlU=,iv:FJgs00oeSDtPfk7RxiMtvQ9pOCxweR2YpgkAYzR2JZA=,tag:i6mLyJpFaHwvQkF1d4BcIA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  name: onepassword-token
  namespace: kube-system
data:
  token: ENC[AES256_GCM,data:JXtKYBbF4adEihYEedisBV7RBLaz21RJ6aDhSKJGkPLweC4bLYMrewQ9nYKkpmEP/zuV3EusFbd+JQp7rOflSNh3I0ey0ihVPRv+N2V2YTfP/LIGz1JFXe9jGDGnS1Q5BldQOn6kIFczSDeYl2gEeXYOzra4/RZ6Zn/yG6OUJt3IaQtUF07t2As2ZQo8LhDLoR49SapXP/ui8oca0XiggO7fyKiUjG7akwGPYrc0OWQwIJSQX3x2ndyexEPuDZI1agnuT0zABYCcogmUTXKAvygExRV9JTPwxpIKKq29HOjDSEUIqz5H7sPfVITvRfFWulr1213PDon/+5O8dUsmfrrBB3r1p73DZ3YSGMITFYA+B85QefY058O+2JFbRgGP1yoKLy2jlxxMFLARdlAOG3o7IMK5moub5hmDKuklXyAh2Wa6g7ZII7euLupQy5g2SLi0vlll1aqwfbzxiU2vCQ8+ApcOjd6uWpjKhjSTX9pxvMFt2r8rw5JRPgEmiwARbCzVt2lT5Jrt3dxPwWsLbabWf1uMyv3diB/+7uWnUV45G3daVj/5mZrDI1haV5nGl7vnP9rd5NZblEKnrC6dLCbXYeBmyKbQI1qKPCiS5maTJalMEJ4aXZnYIf2W+ndR4nlaEpOz6uniCuKfKGaM+ZgC7CkL21JWPJ3qXEHWP9cbA/sTw5MV9Gs3W5B/NKqaTmO8HEVySW4Nn3zelzEBAG7FEetpv4d2i8CnH0hPLuD76YoUxsO/6vuiBsXBRmXL2RusVsSSj27nQ5+ugsNwDk9V0aPCyUDYRz4RE+orGiyCxsHxThqDv+1eYd5Kwr919D8rZNYJg3cyF89ASr9n65k=,iv:YGF9gPrudxzB5/nzoFP23FsEfVo9VJUOH1sM6X9a6s0=,tag:ha483s2WS7uZeUqsZaK9pw==,type:str]
sops:
  age:
    - recipient: age1avwy9taq3crjetrljcd974j7q0wn6mxvcjl7ca7zlm79kv5h0ccqjj457v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsdWpVLzFHcWtRQytvNnNn
        bkVWOFhmWjBsWlFOeFJoaUtJbVRsV0lqTUhNCnhrTEIwcjRaRXBJOHVxaG11cGJB
        TitUMEtTNEluUlVYM01ONTNuRWxMZWcKLS0tIFJZU0gyanR0UTE5bHZPNnEzNVBR
        ejVvSHdqOFB5MDlXa0JDV2Zsclh2WmcK9rTotI+H5H1F47bC2T+5WZoXxvb2I/Gp
        OzXSJ0se+Yz8Zsitut8DsKEXhiNhFBeeMk80jVjWLmAeRDV3pY1Q/w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-05T05:12:44Z"
  mac: ENC[AES256_GCM,data:cYR/76WNaJifiD50Icbg3nyf4JblFhW/IXniR9a6Vr94dF7Z1WGDDpXnicCrvwnCrN6rV1dj2vbM3l5WVbzFEPNszVEb/DFteSzbN8xZ0B3fNts9FIFWnrhya5wc6/NiQXxc8G3PiIzt2QMBhN/Y4cNtYF2FXCqVjWm15cVHzlU=,iv:FJgs00oeSDtPfk7RxiMtvQ9pOCxweR2YpgkAYzR2JZA=,tag:i6mLyJpFaHwvQkF1d4BcIA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
