apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:ZHFyZaGucunqVy8jR+48Be/A/dE6OJzB8qg+N4u+O7v7bRBp4dX2sg==,iv:xWtX2MT9DYcpUKWdqzkTLkho8GMH7uuxvLuDqK+dFn4=,tag:pPRsv20kXNXp6ExbZ3PdUA==,type:str]
sops:
  age:
    - recipient: age1avwy9taq3crjetrljcd974j7q0wn6mxvcjl7ca7zlm79kv5h0ccqjj457v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYNTRBaGlUUTZMSHN6MjNL
        OGd4UlJaYnhFSXkwM2pkbzdqcjRFSXc0RGxZClhKMVpYRUFrL2psc3UrU2Q2MW1r
        cStlNWVPR2RoWjBVbjV2N1U0aTYrQW8KLS0tIGdmT1NvU0NSOElNVXluUmRvVlNT
        K2lJT2d0cSsvUDM1R1c3eitOcmtQQlkKBlgNWy2MPDOPZonBSz8a31x60EJCorGq
        fySwwg+nw9KyAbbs4anfkpWyqdOqpg9LuqtCg6n1ojQmHTFPOquhlQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-23T20:33:51Z"
  mac: ENC[AES256_GCM,data:bavpEBI3v/lvpgaO8KVRCa3wQ4gCMUWJ8GpFSrY9kSL/yq1AMtbelTSIvTd25nRJHO0xUGT3/wnjnCLZ9x1B/Sje1Cs7V7yyZPgkdPL5ChGW/RmZvxiOwUibO2mhi4I5p3LLjCQg4vJTLBKWC650kFBUvlvHMbd7egAGf5/tv7E=,iv:29bWVZx74AncmORAKETLpHiw31tkBVMCuF2HGd4f9qI=,tag:PRf4BCoCl3gbOMN4HY38Dg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
