apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:bDD0SGZh4YArdEmp2e5/DwvwtCQJPvSAv4vkQtztcScTayjYxgL8Mw==,iv:YQOGyGfTrLYuuHLvZ+poIvFUPaqmfUUg+2AG6xTh85A=,tag:C2zBfInUfxQC5Wsiuptm9w==,type:str]
sops:
  age:
    - recipient: age1avwy9taq3crjetrljcd974j7q0wn6mxvcjl7ca7zlm79kv5h0ccqjj457v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0MFhRQUlHNVRDclY3Z2g3
        cjBEaUtEWUVYM21MdmZvczE5RExlZzBWenl3CkdZSGdZV21QK3psUmZZMEFoZmZP
        YXh4RStOcWxMNi9LOFJQLzhwMHJLemMKLS0tIFVabjRRYmJ0M2pWeHNvLzJ2ZDBX
        RTQ2MDlrMDFLSTlacXN6ZTNQNmJpbXcK3E65/R4XS3Sommegj5019ctKgJpUYjhO
        iXHel8HK0I44UP0uhx3SCX2gO5X7fQxGiqj6564iXQWRSdU14EekHQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-20T18:25:24Z"
  mac: ENC[AES256_GCM,data:vonWITxzWR94qAxwKvotq/eXG8T/llm0cYbngqB1zNe//JEN62tiSYqXuy7I83YgcvH6P8jHOnAmEUA9Qf5aNOfDawLcXiv1eWCYFlfoyUicfVADdE4AimUEqMGgz4mhINvW0QCHQgRqnJaV521s5Wa/S1zQfhEJGM6maxXqfVQ=,iv:Gtb4w5Geqo67VPbR3+YTh2HG7fF0vrNRtQ+47mjmuKM=,tag:tVzIFYY4x179kteMhtNP4g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
