apiVersion: v1
kind: Secret
metadata:
  name: ${APP}-volsync-secret
data:
  KOPIA_FS_PATH: ENC[AES256_GCM,data:Yz3v2RyWd5bglEc=,iv:0IO9Teex89Ac8FKo85tcinK0Q+BBGxjMASghwhkBgO8=,tag:aplQEzH3P4BtjBajlr0Rzg==,type:str]
  KOPIA_PASSWORD: ENC[AES256_GCM,data:QxnlgOGb82d/Hp/xsdoVz/DuWFXjOFFv0bVRmlP0U2NiniCn,iv:VxtUjOJpNd1U3pDW/GPLK0XDEgFCPpFallrmf5ZCyd8=,tag:GBJj92di5IK8XHepwkauDw==,type:str]
  KOPIS_REPOSITORY: ENC[AES256_GCM,data:EpghBgidawxu12571qWcWuki0H/RtgHd,iv:zt/uJmV58mfRDpH08Hx1NFCIj62zxMz+zmDK76NMXxU=,tag:sp1uYl0XFDXVaokeiseNTQ==,type:str]
sops:
  age:
    - recipient: age1avwy9taq3crjetrljcd974j7q0wn6mxvcjl7ca7zlm79kv5h0ccqjj457v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtd2xlVHdsbCsxVUlEUzdW
        dXh1T2dhbDBUTkhoTFVSOUlkMzAwdUVLaEFRCmNmNXVldlVyWHV1bjU1eXdWQzlj
        QlVVOUVGRjd5L0pkUlhUT0ZGMXZtWkUKLS0tIFkxcHUvcEpWdXlrRzViQXJ2WUs0
        aGlpLzJkblFDeGlQemlvNFk2REN6YkUKSN45aFAs4gzf89vXUA9vqLwLrSapoERU
        +JBjY5YhDS/4f+sINQs9ER425jd6NrzrnSmirRssxxN0EJC1L9/f5Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-17T19:33:02Z"
  mac: ENC[AES256_GCM,data:5Z4YZ1T3+wYrcxUGnYDZH8lQAwxmQjPaQe9wYbEvULDGi5PJArheX3ebZXcUccW4O+v0V2xLkhniJ10qYAwKV5wKEEMwE8si3i5/KQd9w4riJ0LGDo6geQhGWsrnpU2tg2YkPx6sidyUi/8Aru3GOS/RMKz9mi9Edc4yf81DIlE=,iv:gaMNBnYO7SY+PyCUGBM66aECxiqJDmouGRXEjfIpvEE=,tag:uifIsoXKA+VE1mPYc8Ofdw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
