apiVersion: v1
kind: Secret
metadata:
  name: ${APP}-volsync-secret
data:
  KOPIA_FS_PATH: ENC[AES256_GCM,data:Zh+OPrVgmvblw+8wZtLBzg==,iv:25AKA88n9uR3Ndhe+wBYzt1fFs//vzA5W7fz/ZXPRB8=,tag:5Rn/KO59u9gHUUFlKqVPhA==,type:str]
  KOPIA_PASSWORD: ENC[AES256_GCM,data:mzwCOoLtJJEn4rYINYZBPXoKt3rulWW8ZxsuMF6WUynsNLaf,iv:uBMHtMXfA0UHg6h4zb1erTYmdZjzXsDxSnuNhitfIpk=,tag:cUhLtRWYwT0QAG3GikuTlA==,type:str]
  KOPIS_REPOSITORY: ENC[AES256_GCM,data:kG90aBscr5gJ16YUL52dzGqRR+flPF9uvYG3+iyjiZuQJ8p4,iv:sbVlgR2XR4OzKV0V1MrxZI4n9lGXF2WgTlzlAyrJp+E=,tag:egVPHtSNSXVjhioE9OToMA==,type:str]
sops:
  age:
    - recipient: age1avwy9taq3crjetrljcd974j7q0wn6mxvcjl7ca7zlm79kv5h0ccqjj457v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5bDFQRlZ0eGxwTEtkOTFQ
        VW1mUjkrODd1QjVoNDJZOGlCRnlUeE9iZlJ3CmljTy9sZXU5SUlxaDZxZGNhWVlj
        SHA1VzFYd2JvdHkzTEl2SktsVlNleWsKLS0tIGxHV2RkWStQWFJXSnhnRTA4bElF
        ZXRjZXBCWE9KVkFvbXBhMDhxZWRHY0kKspO3Zj5aB9j8RYThNcvi6TcW539FrLzk
        NgyBBCqB2gam4GBst51ivu9WKf9ekJm80lyv3DuYEx0fgMLYeugvng==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-17T20:03:25Z"
  mac: ENC[AES256_GCM,data:5fFBNB0MA9tTngLjeFTMIoPtK9/X5/I/+wa5Yj0T3yjBfeYjxbhLOMxB0qCmsE1w9AovIOkzSGZ7nirQOx1SAV+iQxUWVHpxt2xA2Qxp+Z6H+e04QdZdHrimxJ/qBssL0HfyaIX0FzZIv12NihQnuF5cRrnZZ6w+dNRMoLO2J3o=,iv:mdlRk8ITaiNJQ5EY7NnFp4nPtliy+YS5hIrsXNxAiVk=,tag:geFL3qr8qMHeaQjG9pKYQw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
