apiVersion: v1
kind: ClusterSecretStore
metadata:
  name: ${APP}-volsync-secreat
data:
  KOPIA_FS_PATH: ENC[AES256_GCM,data:feglAZd3q3QbIlM=,iv:PjnzmGwjsXDLbCcr3szYBNJodK8xvzIn+4GYMfMFe1k=,tag:mT/jXqAILNPwN7biJZggTA==,type:str]
  KOPIA_PASSWORD: ENC[AES256_GCM,data:4WcRDvmRO0GE4cfaUEHygRUBbkaBLfWsJzv8P3SKHfR0KsyG,iv:T+19a72cHtkYh9tNIsxLsh2Yl75sHicsKEb5tVG39cc=,tag:i/xPWJhy5h5MQlSq5ZNHuw==,type:str]
  KOPIS_REPOSITORY: ENC[AES256_GCM,data:luPt3ZtfPosheRbqpEie6hz3YbCgc0st,iv:ILzzXcjJfPNcZLys2pIEXr6bpo5Prm/NkXCchNLxU/0=,tag:SGYRKgT2iuNWpjbDvSGNSg==,type:str]
sops:
  age:
    - recipient: age1avwy9taq3crjetrljcd974j7q0wn6mxvcjl7ca7zlm79kv5h0ccqjj457v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpeVNydU41TzAxcVdFbDA0
        T29UUUYzN1JEemhyRnVpcVdCbUpmaEM1ZlEwCjVXUG9XS2R5dUhnRmdLUllpZkk0
        bllzVlJoc1J6RlRiYWZlVHdiRmNzN0UKLS0tIG9PTmpJbWNPTUJIeDhjT2ZXSXNS
        dFV6NkYzTzk1N0h6a2kyM3lMZFgyRFkK8DnWWLHqT3TheMYQNdNi3Qa7H3l53VI2
        c+AgvvGP1K7cBxvQQuvu0vbY7qBuR6w8Jdcb4heKga85NGgk0xovdg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-07T06:32:17Z"
  mac: ENC[AES256_GCM,data:lvcOpq6Xe1OvAbjR9EzR2RyPCigNKtc/dRcKuTKGC5qK47fzcoTakJHkzEjCYgxGGL1cccNpQ4SJxpPzoG5DRVJEAfjzHqzeMnzURGK/xTatjpiFT31l64YMfVodv/FSCxn6z0rsflVZfW4F1dwDtPS11Z3FKnd28veMoppBNdY=,iv:VpqvY9y6pQtSk/FIkHeeEoWaofdJJ0bm27Z4sXB+j+c=,tag:uLLjqprRn2EwsoPXJTn3GQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
