apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:R6eoEl1bawo=,iv:MHAF2qMNb3nNFGSXjEY4cl5upMC/1v+NwozGQ+BDWn8=,tag:EPAVXM7tK1yrIY3+VykX1A==,type:str]
sops:
  age:
    - recipient: age1avwy9taq3crjetrljcd974j7q0wn6mxvcjl7ca7zlm79kv5h0ccqjj457v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxZ3Z3WmlXTzRoVmM3ekZq
        eFpuWjlJQkMxU2xkTXRWVnc2SE9YZWd0SndvClp0VTZPbGlSckZkTmxqdDRRRlRE
        VUg5VmkyeXNVS2VKd2ZnRk1UZ2VEQzQKLS0tIGpod3d5QVRnZ1cxcS9vZXlEek5C
        RUR4djBuNzBXSHRvQkR5Rmt5eDNWRDAKIdGNC2x7CTcwKOEwokEHqztjLqV/ue/o
        zpX8CTJI8g1FuAZ7Pwe6b68H8XuxvbDZDHlRbbM2Vjk5M7tr1fqKkw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-20T18:25:24Z"
  mac: ENC[AES256_GCM,data:0EoYTLG4WQ+FcEINGZ+3PdkjEALQuzjYNPKGxsLNljmlQK2RgpEs6KpotTqkf9nhDj4DB+ZJSi+z6cjacyD2HnPSV54jnhUEjc6Sal2iOeAgh8d+69+qJj/LLO66eylueBsS3bSV0h9q98hmZkICVs/H6/y8AZEws2ZsX4fmxq0=,iv:4B0nfBYj6BZ5LvP0/dSvZUAMNBDkCZtkem2SWKyQAR8=,tag:uNRnRRkjN6903HMCkaEIfA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
