apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:P3rzU6NtylY=,iv:FSqn8SwKFogbgy/DIHpnOSQ7F7HoX8/wmi+04caqBQA=,tag:F7+x4s9elCre3obyNAqTFg==,type:str]
sops:
  age:
    - recipient: age1avwy9taq3crjetrljcd974j7q0wn6mxvcjl7ca7zlm79kv5h0ccqjj457v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqRThRY1VuSkpoMHpjVFVx
        SXUxZEJNelFiaTNkeFZEelpEUjliemk5eFFrCmNXSmpsclR0YU55RTJ1TWhXTFFW
        c2dTS2dZZXlUNDBxWmNmeENLb2REYlUKLS0tIE5Hd2o0Uk4yYm5ycS9MRUF2WFJQ
        NHlEV3pyVGVnOFZvMzIrNXl6M1ZJek0KvMgJMn79XHV1elroQwSHOVgE5Gb1IuD+
        7Q7Uu2e+FKGZohbCBsAPt983ahYvYNjJF1NdhRXxUxe7dXuBpFppnQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-23T20:33:51Z"
  mac: ENC[AES256_GCM,data:JV6qxBlYvbEYr8kBzRSnNjS9nczThbza/MjlfR3hiyRVHsJftwTebw4l0GbyqSzZYrdxPrPAUSV29khHtw9BEcWTY0DEb0Ny70II12gzxroPLRrmW0SUQeZ6gGyACmEz86L4mtQBmDp7wYvRZUK9MiB/cmUil1rgN9QNtu8aWxo=,iv:EKUQpsK7Wc8h/h6t1EjaVt18jIGzieWpbw39i1V7Ijk=,tag:0M7NuJsFKjSc4p7TDjrOlw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
