apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:Y04UjN5sFIA8f4lFhiCJZg1EZB1Q6lxs8y0vOINMSe0=,iv:7jBbDyTsqzztHpLEFVISZKrZMkO2v1mvAiiLCqGDzn4=,tag:76jqwF72JwJEoYdP9BkKJA==,type:str]
sops:
  age:
    - recipient: age1avwy9taq3crjetrljcd974j7q0wn6mxvcjl7ca7zlm79kv5h0ccqjj457v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUMHhwWkdJR3Evb2QySFRD
        RExxWDBCRTk2ZElBNFBLNUdRSEc2MnpLaVg4ClpkeVUxeGZKb1drakZYaFRZM2J3
        cWsxdnpaVFBJTUpYQVdHOVd0VUhlQjAKLS0tIGtLN2ZxcHdQOXRVclZxckZvMVY5
        ZDRVTjBsUTNuY2QxRkFsSmpFT0lqenMKIgBC0VjjbOHX+2GEj0osEN1l0hF8xU+B
        ntlhQvSRZaKwHEHO/4Pft/sVoxn39/8R564u0aBTtKcebPjkLQE8uA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-23T20:33:51Z"
  mac: ENC[AES256_GCM,data:SiZ/s58daBqmc6Trlzm2pru2gkKr3DWjKHntwfXdHjbuDTsS0HnXCkHJurIV8Hl/8aM1U0A9xJVAy/ZUCFeIcVTv9Hkqio1DtE2LbHlg7/Jv7C5+zV1rycn+V7zF1w2rT/+wfxKeriZBF6SCQ4S5mKYRPATihqFOnD6FLZIrNI8=,iv:cS8c6DKCpOROxw/wQJo7QjmKJsR1uOcjZycxTwJmbH4=,tag:fFV4/ZDzVVlAUNWm3UnW1w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
