apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:dsdFcYGpci0GcVMusFuZXrV38YIkm+yoSEBOwQ89GcI=,iv:KKEecO/DrHGz5w17SHgPZJPmLVPMfYAHKTBUpFXyQ+8=,tag:avbe5ZX4yalmgJWKm0dSiA==,type:str]
sops:
  age:
    - recipient: age1avwy9taq3crjetrljcd974j7q0wn6mxvcjl7ca7zlm79kv5h0ccqjj457v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjQWhUN2hvRHdiR1E1RkJ1
        WUZaUWF1M2pOYzRiZkVNNnZZaVdudGd0VUN3CkZsOGxGVTU2N3FwZlNyU1ZMK3Vy
        dHQ1STJOZnA4eXRKeGVMbVV1UzFZOEEKLS0tIHRtckhTMmN5WW1ETnhFaHBKY2x2
        bzRrbmlHYkZnQUIwdmlPTTM2NWNQRmcKrbQTqwKusZXQQiQlvMtoUjYRU660EBzB
        gHfuqU6qR+AH+wDCTvFK3NDgKojOUELxOg4D3TuEMANlXIGVMbUV+A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-20T18:25:24Z"
  mac: ENC[AES256_GCM,data:5PfBzTIZrAo3EFFh3f1yHkOgNkvyH24DUgFBKptToFs91MLKsuesSeLxKrMBszcXPSITSEYjLQu2bK64AWNjodMrY5eFfYPKZEsqm4dyxF7laKJ9NKBsd3y1EANSXowaa5giftaJE+aGQzr1km5EvpR42J8EsfE7x6wYMxZ0N58=,iv:pWfpRnNiG1WPwrORFmtBUFCtagMMehjLbbwCySskozw=,tag:rfP7P4nkPSYFdGTriFD+mQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
