apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-credentials
  namespace: observability
data:
  GF_SECURITY_ADMIN_USER: ENC[AES256_GCM,data:+EWbRI89Zzs=,iv:Y1iy2WZlzQgYdgLuRWqcqGP5ESPyxqwdOu4TTDVVKAw=,tag:As+mHZ9uvFGEhlGx/EWW8g==,type:str]
  GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:F93djiyKU7yZ8M7zoywIN81NlJZ8WSJKntzmC2Ke00+ZO/7s,iv:CzlSA4YJEMUwMcHsQrWT6P5VaRgIqeufhXvjcF1bHz0=,tag:l5u196IagyFKMEctXoZ/KA==,type:str]
sops:
  age:
    - recipient: age1avwy9taq3crjetrljcd974j7q0wn6mxvcjl7ca7zlm79kv5h0ccqjj457v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLRFRqREF6a1BBU2crWDRY
        Vmx6Nk03aTRzMTh4YVgvY3N0Z2lOOGNWaHpnCmFIYzkwT1B3WWtNLzhjQlNkZ0VU
        ZklPVk5TMGpxZVFjQ3BMOWlsOVhWd28KLS0tIDVHZHNPdHNEWHVjSU9qeHlVMkhE
        anNWVkRVMWYxQ1ZPaGo2MFcwdGpYT0kK1lVTaP6KNtByDe71RF80dPjgqGXw/moX
        biNELLPvq2zqXEhctX6fAWOCK/60w5bWojMwryRBfpL9B9D5xdptfQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-06T22:02:11Z"
  mac: ENC[AES256_GCM,data:y+dLP+gCtFZ9FsoAGld/vW3wFftdZA2GJL4VNB2ktQ6xpN65azDr16HhTfG0i5xTYCgm2cidv/xSFbto5TKpcMVzPVje8N0TbrlJFb+g/2pRUK2GFUy3D6vPB0oBu2VNFn6T+IZrm3Hx/3iYMTuabDAvB8Ru+eVlDlOMm7yro/U=,iv:LBndE8HS/LVyiQGTbuO66jUDEksfNuY24Fsm2eTL0rQ=,tag:Jk4bzjSsXq2Rgcs7BbYyKg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
