apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:aaJTtc0d9Fs9ridhTQX8fNr890gD8mjin7SSBsXhp5fChrwzaNnibdGrhi0uM3I5mz8ied9ipWLXNDPq5Z1iadZlS3wNqnNRH05Ie+UbneHUJKjJhsemi4ofxNGzLav6aJmtBJdnC5XnmsUuBSg+tUxb09KpBdrtK0fFasFFjewwvhB/jIL1wBpeiZiX8ENZmCsFI4MW1obKo8Dz0J4Tj1TaPB9ho/X2QwQG7ATyrwGVfbT6,iv:XBOt5h6TojOtehyLAFQNC9Lv3hODkBFm6Xj6RZsZA0M=,tag:23YTk7NMQ/uuo4qXst+idA==,type:str]
sops:
  age:
    - recipient: age1avwy9taq3crjetrljcd974j7q0wn6mxvcjl7ca7zlm79kv5h0ccqjj457v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwN1NvaE9oWnltaGRtQ1dw
        RWhRVCs3eTVzeE83UG1FR1NDcGIvdWdRVzNNCkxiTmhMNDQ0bDF4Wkl6OUxyVEE2
        UUtwckFLaWRCTjczakJPTVlwV05YTkUKLS0tIHlGOWNJaTJpSW1ua3diS0pGQmxX
        VTIreFhkY2NuTDN5WlBWNzFnRHpRbDQK/uV0UJymM0NB7azwNdeuv5QjBwhod5e6
        8Wfh9syeoTHoQDN5rUtoHjrchSm6A+/q0X1BnYwXg2Zz1ZsoV6j55Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-23T20:33:51Z"
  mac: ENC[AES256_GCM,data:422/LtwmEudhrjfxHlzNCgXYirg14t/kR5tfAIXD2ROifc/WGHOAH1f3lSnLhhAnmvFpnX+pEo0BphkW8GYGcLD0T7SkJQOGaX3CCOELJXDOSlEhkzRe1zmqrpriOUlumj10mU264wnbGewsUtPzAglf7GQKHECK+4gqEZ2xtLA=,iv:NKsAKCbLmBi2cunF1Xk9zanpxiwKPGiZk+CY5nCt6WQ=,tag:rrJsgwOthLtSH0q+6wwvoQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
