apiVersion: v1
kind: Secret
metadata:
  name: sabnzbd-secret
stringData:
  SABNZBD__API_KEY: ENC[AES256_GCM,data:NgBm8P7MHXSgutD+gjN23OXL0JLbme9nT/gnrYZhw0I=,iv:mZOsz3bRnvFKAwme5dV0a2ZRq1oBPR8S9h059mtNxZc=,tag:A0BheH5Ju+MUaHYK5Q5Sqw==,type:str]
  SABNZBD__NZB_KEY: ENC[AES256_GCM,data:dCmvBVBG6Zw5MwvlSEOfoQVzmSAVtoUS6iKy2JM38XY=,iv:kQhv3K2gXdugGjyobQXTx14OK2xA6ASR1bPRyMnClp0=,tag:H/nvlRSCS0OZzCDc3rAdqg==,type:str]
sops:
  age:
    - recipient: age1avwy9taq3crjetrljcd974j7q0wn6mxvcjl7ca7zlm79kv5h0ccqjj457v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1bld3TjArVStIN2FwQ1RD
        N25nUWtWZWlXMDNEdWRSUHlMMUZyRitFYndNCmlmNUw4a0taNm0wR3JqakY3S1h2
        VUt3SXBTNzdaaDYzMU1rbkpNNWFNVFEKLS0tIE81R3hFWjJndlVUKzlCVU9JMWwz
        cUxVSC8wMHJ2UG9ncndEYzMySU5oVjQKAhJ98/4ebDg2EAm8iWTM+of4Sf7hyPOb
        cQnLWlIyr9bfUEbsUOIJ95BXBDCLuiVu89BJWTiJ8bcf+7dx99hMjw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-17T17:56:36Z"
  mac: ENC[AES256_GCM,data:CN9HKXwr5xrpDE5wfKe/wn9UH11xnFCN+9ZvI4BkZpFS9f1H1nG1XZn69RtX0utUvaJBgDUGGf33lvfp8G+2b2cxOGQwv50GQuGcYpQkSS12+KyJyt0tKx+wzJxT2Utypt/7kJNK47JSWVceTyZdIxi74RyxY4uYz9TH/BEKJVQ=,iv:K6OqEj44KNYUuQe6WvU0HVvllHnTWnNV6mhk1xljANw=,tag:NPzzjHtcutYjcdLE8HXVfQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
