apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:hoTpgoZoIgXjb4SOHmWPRsj1uUpNWWorafzyDjLYJIm3kyZzw1z3OQ==,iv:FtcqtZk4S0NHa7SkQAOoqJxi2+nJ+I/eVq9ePwq6mEc=,tag:dWAasZ7yzPp9r+KUcokkBA==,type:str]
sops:
  age:
    - recipient: age1avwy9taq3crjetrljcd974j7q0wn6mxvcjl7ca7zlm79kv5h0ccqjj457v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBic3Q0a1A5YmtueGJ2MWcy
        bERqR2NmalpJVXJndlRRODNGNWk1WmxRaG1nCjBFZkhsWWhTbDJiZ3Y2dWNEcnlK
        QUJMWDNXOE10aFlGV1A5SnUrSUU0a3cKLS0tIGliS2IzMnJ2TkVncCs2cUhJK3hj
        NXpiQ0JPSXJMclFZSHp6eWIyYngyVjgKXiDaXSX5X1C9fVdZkLAWKIEmFiAGNyFk
        IIi0VOkclHRdtb2KH73AQwCjQu6imM9/rxhKZEE1KN9fbwXu8UlyNA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-20T18:25:24Z"
  mac: ENC[AES256_GCM,data:RrmL/wgbdpe7q95mCe7LncWq99rM9tJB3Juvv8GRkxESnucsCmDIAnRirbv1Jmt4OsH49Q3P3bKC0yy1VaatDmVetNudNjJ1H+CPmtNpfqDwMMwQ+xBvs8LdFtScc2j7OFALmHvUli/YJ/4SBQ9Mch6uvcqonrR2RBMJvRnxr1M=,iv:AXzBE/e0qatvfamhg7AI7t6xLm/Nsd5vV/luNp4rVQU=,tag:O6XaeLP9qSct9D8VP9AL8w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
