apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:rtz07bXoC9YRK9AgpurzSGc+t9tUUOB21Kjj9H8rCGql/xQnMZ/Ybw==,iv:kdmP0NE5aPoVD090so4kp/ww4FJWJboiPEwVHjMlN8A=,tag:ZQfAkW1AnoQElBQGyfB4Ig==,type:str]
sops:
  age:
    - recipient: age1avwy9taq3crjetrljcd974j7q0wn6mxvcjl7ca7zlm79kv5h0ccqjj457v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5VGgyeW1rWWpPRXJpZWNj
        czJUR3BPVnlaUzE5LzI3VWN4V015UFdodnhRCjY3dXJraGtEVkc4UWloazd0SjR1
        OGRVbC8zVDhvcHBRMUpJL1k1MW90aVkKLS0tIEZFbTBja1dwZHVUemMwZkd1eTFu
        UmZEaVJuVGhnbjVZaUdYTGhEL0ZwSjAKA5AlcJ4gtlUt4syNEdkJN2DBRBHmTm6s
        34XA5EbDNiMHljtfuGKrcEMhvaTCNE8qUDzw+CHIWfAmD2wXyUSKAw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-23T20:33:51Z"
  mac: ENC[AES256_GCM,data:0f1KfxXSBKyO1wy9V+tlg52xkiPmjgK/IDDRuJRt8etyZnrYxJcxOFoEg1kCMaWcQyxI5CxoBjxS143r/y2qFClXGhOSw3foxTiZWqCEzvoZtOYYTj4tnpXLAdP1Ja7bk1iyf60Om9b3z3uSAgpb/rGtJ5LNT+B9SEwdPmWOiI4=,iv:wh7bjfMwuEWY5UqNPXS7Qoqa15axnfWUsitTa9Y+EAY=,tag:gai4D5xMqaQWUV+Ytbcteg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
