apiVersion: v1
kind: Secret
metadata:
  name: kopia-secret
  namespace: volsync-system
data:
  KOPIA_PASSWORD: ENC[AES256_GCM,data:3300yR/gMRWLD4KQ8P8VjX3ViCCOWXQTa6UGChGB1/pEa6q0,iv:UbsbOAiXE0EBjVpWzK9jhx9+RFv3RQWznbqgMqRArJA=,tag:lM2KXxSGZv3NlSPsM4QwhA==,type:str]
sops:
  age:
    - recipient: age1avwy9taq3crjetrljcd974j7q0wn6mxvcjl7ca7zlm79kv5h0ccqjj457v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyQU85WldCUjY1Y0pvUkJu
        M3FJTjBxNWhrWVovbXN3aXQ4U09BSmcwOENrCjVsUnhUWW9JSi9lZzVIa3A3WkZH
        M2pmS1UxeGFlenkxYmlnTmhJOGM5SkEKLS0tIDFYMHpBSmRRSFJ6aTRJOCtXRkFs
        U0JRaUZrTjQ1d01ySlYzU1ZKYlp0c2sKHlp0wCjDuAa/z1wp44fqi7WuKJYNTfVW
        mNcDxkl6iGIlMPhjRbKykR+W4RmMTsy4LdzQvmXDwihGRPQ+55ajJQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-07T06:16:50Z"
  mac: ENC[AES256_GCM,data:zDzu8TOgCZWekkXVl3yYp6WSvAhdem3daS2ocivD9/SuXt889arr000NMnUqhmbNapVo8oZgMNbzYfGtyay5po24RxaytxDsZ/jnRkcMGqQUyW6q3jOCfoaFK2HiZDn4tIUZ5l/ovWWbNow7ttXNMvqG2zqX3ElthSXsxWKA3fI=,iv:39zBDDCHMGGTXFgzwG9lAP+i5oKBDfTiBvFKCTPem9g=,tag:xYGU1bq0JiAsKf7AL+ywXw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
